#if UNITY_EDITOR
using System;using System.IO;using System.Text;using UnityEditor;using UnityEngine;using UnityEngine.Rendering;using EID4730;
[InitializeOnLoad] public static class EID1721ViewProbe {
 const string D="D:/endcopy/EID3336_URP_GBuffer_Workspace/.rdctools/eid1721_colorfix_1001";
 static bool active;static Camera cam;static string run;static int phase,frames;static double next,deadline;static StringBuilder log=new StringBuilder();static EditorWindow oldFocus;static System.Collections.Generic.Dictionary<string,int> counts=new System.Collections.Generic.Dictionary<string,int>();
 static EID1721ViewProbe(){EditorApplication.update+=Tick;AssemblyReloadEvents.beforeAssemblyReload+=Stop;}
 static void Tick(){try{if(!active){if(EditorApplication.isCompiling||EditorApplication.isUpdating||!File.Exists(D+"/request.txt"))return;run=File.ReadAllText(D+"/request.txt").Trim();File.Delete(D+"/request.txt");active=true;Shader.SetGlobalFloat("_EID4798DebugMode",run.Contains("flags")?1:run.Contains("basisfix")?2:0);phase=frames=0;log.Clear();counts.Clear();EID4730RenderFeature.HairLegacyAOForDiagnostics=run.Contains("legacy");EID4730RenderFeature.HairAOAuditForDiagnostics=run.Contains("audit");next=0;deadline=EditorApplication.timeSinceStartup+70;oldFocus=EditorWindow.focusedWindow;RenderPipelineManager.beginCameraRendering+=Begin;RenderPipelineManager.endCameraRendering+=End;EID4730RenderFeature.CaptureHairForDiagnostics+=Stage;}
 if(EditorApplication.timeSinceStartup>deadline||(phase>=6&&EditorApplication.timeSinceStartup>=next)){Stop();return;}if(EditorApplication.timeSinceStartup<next)return;next=EditorApplication.timeSinceStartup+8;phase++;bool scene=phase%2==0;
 log.AppendLine("FOCUS "+phase+" "+(scene?"Scene":"Game"));foreach(var w in Resources.FindObjectsOfTypeAll<EditorWindow>())if(w.GetType().Name==(scene?"SceneView":"GameView")){w.Focus();break;}SceneView.RepaintAll();foreach(var w in Resources.FindObjectsOfTypeAll<EditorWindow>())if(w.GetType().Name=="GameView")w.Repaint();
 }catch(Exception e){log.AppendLine(e.ToString());Stop();}}
 static void Begin(ScriptableRenderContext c,Camera camera){cam=camera;frames++;log.AppendLine("BEGIN "+frames+" phase="+phase+" "+cam.cameraType+" pos="+cam.transform.position.ToString("F4"));
 foreach(var name in new[]{"EID1721_instance_000"}){var o=GameObject.Find(name);if(o==null)continue;var r=o.GetComponent<Renderer>();var mf=o.GetComponent<MeshFilter>();if(r==null)continue;var b=r.bounds;Vector2 lo=new Vector2(float.MaxValue,float.MaxValue),hi=-lo;for(int i=0;i<8;i++){var p=b.center+Vector3.Scale(b.extents,new Vector3((i&1)==0?-1:1,(i&2)==0?-1:1,(i&4)==0?-1:1));var q=cam.WorldToScreenPoint(p);lo=Vector2.Min(lo,q);hi=Vector2.Max(hi,q);}var mat=r.sharedMaterial;var mp=new MaterialPropertyBlock();r.GetPropertyBlock(mp,0);string prop=name.Contains("4794")?"EID4794PS_42":"_42";var tx=mp.GetTexture(prop);
 log.AppendLine(name+" enabled="+r.enabled+" shader="+mat.shader.name+" GB="+mat.GetShaderPassEnabled("UniversalGBuffer")+" mesh="+(mf?mf.sharedMesh.name:"")+" bounds="+b+" screen="+lo+".."+hi+" AO="+(tx?tx.name:"null"));}}
 static void Stage1721(CommandBuffer cmd,RTHandle target){Stage(cmd,target,1721);}
 static void Stage(CommandBuffer cmd,RTHandle target,int eid){if(eid!=4798)return;if(cam==null||target.rt==null)return;string key=phase+"_"+cam.cameraType+"_"+eid;counts.TryGetValue(key,out int count);if(count>=2)return;counts[key]=count+1;var rt=target.rt;int w=rt.width,h=rt.height;string label=run+"_p"+phase+"_f"+frames+"_"+cam.cameraType+"_"+eid+"_"+w+"x"+h;
 cmd.RequestAsyncReadback(rt,0,TextureFormat.RGBA32,r=>{if(r.hasError){File.AppendAllText(D+"/errors.txt",label+" readback failed\n");return;}File.WriteAllBytes(D+"/"+label+".rgba",r.GetData<byte>().ToArray());});}
 static void End(ScriptableRenderContext c,Camera camera){log.AppendLine("END "+frames+" "+camera.cameraType+" CP26="+ColourPass26HairPass.LastDrawCount);}
 static void Stop(){if(!active)return;active=false;RenderPipelineManager.beginCameraRendering-=Begin;RenderPipelineManager.endCameraRendering-=End;EID4730RenderFeature.CaptureHairForDiagnostics-=Stage;EID4730RenderFeature.HairLegacyAOForDiagnostics=EID4730RenderFeature.HairAOAuditForDiagnostics=false;File.WriteAllText(D+"/"+run+".txt",log.ToString());Shader.SetGlobalFloat("_EID4798DebugMode",0);if(oldFocus!=null)oldFocus.Focus();}
}
#endif
