#if UNITY_EDITOR
using System; using System.IO; using System.Text; using System.Reflection; using UnityEditor; using UnityEngine; using UnityEngine.Rendering;
[InitializeOnLoad] public static class EID2916Audit1005 {
 const string D="D:/endcopy/EID3336_URP_GBuffer_Workspace/.rdctools/eid2916_fix_1005";
 static string run; static bool active; static double deadline,next;
 static EID2916Audit1005(){EditorApplication.update+=Tick;AssemblyReloadEvents.beforeAssemblyReload+=Stop;}
 static void Stop(){active=false;RenderPipelineManager.endCameraRendering-=End;}
 static void Tick(){if(EditorApplication.isCompiling||EditorApplication.isUpdating)return;if(!active&&File.Exists(D+"/request.txt")){run=File.ReadAllText(D+"/request.txt").Trim();File.Delete(D+"/request.txt");active=true;deadline=EditorApplication.timeSinceStartup+120;next=0;RenderPipelineManager.endCameraRendering+=End;}
 if(!active)return;if(EditorApplication.timeSinceStartup>deadline){File.WriteAllText(D+"/"+run+"_timeout.txt","No Game capture");Stop();return;}if(EditorApplication.timeSinceStartup<next)return;next=EditorApplication.timeSinceStartup+1;foreach(var w in Resources.FindObjectsOfTypeAll<EditorWindow>())if(w.GetType().Name=="GameView")w.Repaint();}
 static void End(ScriptableRenderContext context,Camera camera){if(!active||camera.cameraType!=CameraType.Game||camera.name!="EID3336 RenderDoc Camera")return;Stop();var log=new StringBuilder();log.AppendLine(DateTime.Now.ToString("O"));log.AppendLine("Scene="+UnityEngine.SceneManagement.SceneManager.GetActiveScene().path+" dirty="+UnityEngine.SceneManagement.SceneManager.GetActiveScene().isDirty);log.AppendLine("camera="+camera.transform.position.ToString("F6"));var go=GameObject.Find("EID2916_instance_000");if(go){log.AppendLine("transform="+go.transform.localToWorldMatrix);foreach(var r in go.GetComponentsInChildren<Renderer>()){log.AppendLine("renderer="+r.name+" enabled="+r.enabled+" bounds="+r.bounds);foreach(var m in r.sharedMaterials){log.AppendLine("material="+AssetDatabase.GetAssetPath(m)+" shader="+m.shader.name+" queue="+m.renderQueue+" RenderType="+m.GetTag("RenderType",false)+" passes="+m.passCount);foreach(var n in m.GetTexturePropertyNames()){var t=m.GetTexture(n);if(t)log.AppendLine(n+"="+AssetDatabase.GetAssetPath(t)+" "+t.graphicsFormat+" "+t.width+"x"+t.height);}}}}else log.AppendLine("OBJECT MISSING");
 foreach(var w in Resources.FindObjectsOfTypeAll<EditorWindow>())if(w.GetType().Name=="GameView"){for(Type t=w.GetType();t!=null;t=t.BaseType){var f=t.GetField("m_RenderTexture",BindingFlags.Instance|BindingFlags.NonPublic|BindingFlags.Public|BindingFlags.DeclaredOnly);if(f==null)continue;var rt=f.GetValue(w)as RenderTexture;if(rt){string path=D+"/"+run+"_Game_"+rt.width+"x"+rt.height+".rgba";AsyncGPUReadback.Request(rt,0,TextureFormat.RGBA32,x=>{if(x.hasError)File.WriteAllText(path+".error","readback failed");else File.WriteAllBytes(path,x.GetData<byte>().ToArray());});}break;}break;}File.WriteAllText(D+"/"+run+"_audit.txt",log.ToString());}
}
#endif
