#if UNITY_EDITOR
using System;using System.IO;using System.Text;using UnityEditor;using UnityEngine;using UnityEngine.Rendering;using UnityEngine.Rendering.Universal;
[InitializeOnLoad] public static class EID3602GBufferAudit {
const string D="D:/endcopy/EID3336_URP_GBuffer_Workspace/.rdctools/eid3602_fix_1004/second_pass";
static double next,until;static bool active,game,scene;static string run;
static EID3602GBufferAudit(){EditorApplication.update+=Tick;AssemblyReloadEvents.beforeAssemblyReload+=Stop;}
static void Stop(){active=false;RenderPipelineManager.endCameraRendering-=End;}
static void Tick(){if(EditorApplication.isCompiling||EditorApplication.isUpdating)return;if(!active&&File.Exists(D+"/request.txt")){run=File.ReadAllText(D+"/request.txt").Trim();File.Delete(D+"/request.txt");game=scene=false;active=true;next=0;until=EditorApplication.timeSinceStartup+45;RenderPipelineManager.endCameraRendering+=End;}if(!active)return;if(EditorApplication.timeSinceStartup>until){Stop();File.WriteAllText(D+"/"+run+"_done.txt","game="+game+" scene="+scene);return;}if(EditorApplication.timeSinceStartup<next)return;next=EditorApplication.timeSinceStartup+3;SceneView.RepaintAll();foreach(var w in Resources.FindObjectsOfTypeAll<EditorWindow>())if(w.GetType().Name=="GameView")w.Repaint();}
static void End(ScriptableRenderContext ctx,Camera cam){if(!active)return;bool g=cam.cameraType==CameraType.Game&&cam.name=="EID3336 RenderDoc Camera";bool s=cam.cameraType==CameraType.SceneView;if(!(g||s)||(g&&game)||(s&&scene))return;if(g)game=true;else scene=true;string label=run+"_"+cam.cameraType;var log=new StringBuilder();log.AppendLine("camera="+cam.transform.position+" size="+cam.pixelWidth+"x"+cam.pixelHeight);var go=GameObject.Find("EID3602_instance_000");if(go){foreach(var v in go.GetComponent<MeshFilter>().sharedMesh.vertices)log.AppendLine("vertex_screen="+cam.WorldToScreenPoint(go.transform.TransformPoint(v)).ToString("F5"));log.AppendLine("matrix="+go.transform.localToWorldMatrix);}Texture depth,mat,norm,col;bool ok=EID3336FiveMRTLightingInputs.TryGetVegetationLightPassInputs(cam,out depth,out mat,out norm,out col);log.AppendLine("gbuffers="+ok);if(ok){Dump(mat,label+"_packed",log);Dump(norm,label+"_normal",log);Dump(col,label+"_albedo",log);}File.WriteAllText(D+"/"+label+".txt",log.ToString());}
static void Dump(Texture tex,string label,StringBuilder log){if(!tex)return;log.AppendLine(label+"="+tex.width+"x"+tex.height+" "+tex.graphicsFormat);var rt=RenderTexture.GetTemporary(tex.width,tex.height,0,RenderTextureFormat.ARGBFloat,RenderTextureReadWrite.Linear);var old=RenderTexture.active;var cpu=new Texture2D(tex.width,tex.height,TextureFormat.RGBAFloat,false,true);try{Graphics.Blit(tex,rt);RenderTexture.active=rt;cpu.ReadPixels(new Rect(0,0,tex.width,tex.height),0,0);cpu.Apply();File.WriteAllBytes(D+"/"+label+"_"+tex.width+"x"+tex.height+".f32",cpu.GetRawTextureData());}finally{RenderTexture.active=old;UnityEngine.Object.DestroyImmediate(cpu);RenderTexture.ReleaseTemporary(rt);}}
}
#endif
